# Generated by Django 5.2.3 on 2026-06-15 14:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('stage', models.CharField(max_length=40, verbose_name='fase')),
                ('group', models.CharField(blank=True, max_length=20, verbose_name='grupo')),
                ('matchday', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='rodada')),
                ('kickoff_at', models.DateTimeField(verbose_name='início')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Agendado'), ('TIMED', 'Confirmado'), ('IN_PLAY', 'Em andamento'), ('PAUSED', 'Intervalo'), ('FINISHED', 'Finalizado'), ('POSTPONED', 'Adiado'), ('CANCELLED', 'Cancelado')], default='SCHEDULED', max_length=20)),
                ('regular_home', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('regular_away', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('extra_home', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('extra_away', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('penalties_home', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('penalties_away', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('scoring_home', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('scoring_away', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('manual_override', models.BooleanField(default=False, verbose_name='ajuste manual')),
                ('provider_updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'partida',
                'verbose_name_plural': 'partidas',
                'ordering': ['kickoff_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exact_score_points', models.PositiveSmallIntegerField(default=5)),
                ('correct_result_points', models.PositiveSmallIntegerField(default=2)),
                ('wrong_draw_bonus', models.PositiveSmallIntegerField(default=1)),
                ('winner_goals_bonus', models.PositiveSmallIntegerField(default=1)),
                ('lock_minutes', models.PositiveSmallIntegerField(default=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'regra de pontuação',
                'verbose_name_plural': 'regras de pontuação',
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RUNNING', 'Executando'), ('SUCCESS', 'Sucesso'), ('FAILED', 'Falhou')], max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('matches_received', models.PositiveIntegerField(default=0)),
                ('matches_changed', models.PositiveIntegerField(default=0)),
                ('response_snapshot', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'sincronização',
                'verbose_name_plural': 'sincronizações',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('short_name', models.CharField(blank=True, max_length=80)),
                ('code', models.CharField(blank=True, max_length=4)),
                ('crest_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'seleção',
                'verbose_name_plural': 'seleções',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PointAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('import_key', models.CharField(blank=True, max_length=180, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_adjustments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ajuste de pontuação',
                'verbose_name_plural': 'ajustes de pontuação',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('away_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='pool.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'palpite',
                'verbose_name_plural': 'palpites',
                'ordering': ['match__kickoff_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.PositiveSmallIntegerField()),
                ('away_score', models.PositiveSmallIntegerField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prediction_revisions', to=settings.AUTH_USER_MODEL)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='pool.prediction')),
            ],
            options={
                'verbose_name': 'histórico de palpite',
                'verbose_name_plural': 'históricos de palpites',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='pool.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='pool.team'),
        ),
        migrations.AddConstraint(
            model_name='prediction',
            constraint=models.UniqueConstraint(fields=('user', 'match'), name='unique_prediction_per_match'),
        ),
    ]
