# Generated by Django 5.2.3 on 2026-06-26 00:22

import django.db.models.deletion
from django.db import migrations, models


def create_default_group(apps, schema_editor):
    PoolGroup = apps.get_model('accounts', 'PoolGroup')
    User = apps.get_model('accounts', 'User')
    group, _ = PoolGroup.objects.get_or_create(
        slug='geral',
        defaults={'name': 'Geral', 'is_active': True},
    )
    for user in User.objects.filter(is_staff=False):
        user.pool_groups.add(group)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'grupo de bolao',
                'verbose_name_plural': 'grupos de bolao',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='invite',
            name='kind',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('SHARED', 'Compartilhado')], default='INDIVIDUAL', max_length=20, verbose_name='tipo'),
        ),
        migrations.AddField(
            model_name='invite',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='limite de usos'),
        ),
        migrations.AddField(
            model_name='invite',
            name='used_count',
            field=models.PositiveIntegerField(default=0, verbose_name='usos'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='display_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='e-mail'),
        ),
        migrations.AddField(
            model_name='invite',
            name='pool_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invites', to='accounts.poolgroup', verbose_name='grupo de bolao'),
        ),
        migrations.AddField(
            model_name='user',
            name='pool_groups',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.poolgroup', verbose_name='grupos de bolao'),
        ),
        migrations.RunPython(create_default_group, migrations.RunPython.noop),
    ]
