# Generated by Django 5.2.3 on 2026-06-26 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_poolgroup_invite_kind_invite_max_uses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=500, verbose_name='mensagem')),
                ('chat_date', models.DateField(verbose_name='data do chat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pool_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='accounts.poolgroup', verbose_name='grupo de bolao')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'mensagem do chat diario',
                'verbose_name_plural': 'mensagens do chat diario',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['pool_group', 'chat_date', 'created_at'], name='accounts_da_pool_gr_2b619e_idx')],
            },
        ),
    ]
